title: Furfel blog
email: hello@furfel.com
description: >- # this means to ignore newlines until "baseurl:"
    Furfel blog. Games, DIY stuff, coding, Linux, business, books.
    And a lot of other amazing things and thoughts.
    Warning: might contain insane futurism!
shortdesc: "A lot of amazing stuff."
baseurl: ""
url: "https://furfel.com"
twitter_username: __local
twitter:
  username: __local
github_username:  furfel
rss: Atom feed

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
# markdown: kramdown # Apparently adding kramdown as markdown processor
                     # causes GitHub pages to iterate through posts and pages twice
permalink: /posts/:title
paginate: 5

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
